import fs from 'node:fs';
import { spawnSync } from 'node:child_process';

const run = script => {
  const result = spawnSync(process.execPath, [script], { stdio: 'inherit' });
  if (result.error) throw result.error;
  if (result.status !== 0) process.exit(result.status || 1);
};
const has = (file, marker) => {
  try { return fs.readFileSync(file, 'utf8').includes(marker); }
  catch { return false; }
};

run('scripts/prepare-v30106.mjs');
run('scripts/apply-v30107-release.mjs');

const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
const checks = [
  ['src/components/home/HomeView.tsx', 'articles.slice(0, 3).map((article) => ('],
  ['src/components/blog/ArticleDetailView.tsx', 'const { products, articles, articleCategories, categories } = useStore();'],
  ['src/public-hydrate.tsx', "await import('./components/product/ProductDetailView')"],
  ['scripts/build-server.mjs', 'splitting: true'],
  ['server.ts', 'max-age=31536000, immutable']
];
const missing = checks.filter(([file, marker]) => !has(file, marker));
if (missing.length) {
  throw new Error('v30.10.7 preparation incomplete: ' + missing.map(([file, marker]) => `${file} :: ${marker}`).join(' | '));
}

const versionMatch = String(pkg.version || '').match(/^30\.10\.(\d+)$/);
if (!versionMatch || Number(versionMatch[1]) < 7) throw new Error(`Expected package version 30.10.7+, got ${pkg.version}`);
if (pkg.devDependencies?.autoprefixer) throw new Error('Dead autoprefixer dependency is still present.');
if (!String(pkg.dependencies?.multer || '').includes('2.4')) throw new Error('Multer 2.4.x release line is required.');
if (!String(pkg.dependencies?.sharp || '').includes('0.35.5')) throw new Error('Sharp 0.35.5+ security release is required.');
if (!String(pkg.overrides?.protobufjs || '').includes('7.6.5')) throw new Error('protobufjs security override is missing.');
if (!String(pkg.overrides?.ws || '').includes('8.20.1')) throw new Error('ws security override is missing.');
if (fs.existsSync('package-lock.json')) {
  console.warn('package-lock.json exists in the working tree. It is intentionally not required or generated by this project.');
}

console.log('Source preparation completed at v30.10.7+ stage 8 release audit.');
