import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { runSiteAudit } from '../src/server/audit/site-audit.ts';

const report = runSiteAudit();
assert.equal(typeof report.generatedAt, 'string');
assert.equal(typeof report.coreVersion, 'string');
assert.equal(report.engineVersion, '2.2.0');
assert.ok(Array.isArray(report.findings));
assert.equal(report.summary.total, report.findings.length);
assert.equal(report.coverage.pipelineTraceAvailable, true);
assert.equal(report.coverage.productionBundleVerified, true);
assert.equal(report.coverage.analysisSource, 'prepared-trace');
assert.ok(report.coverage.preparedRouteInventory > 0);
assert.ok(report.coverage.preparedApiCalls > 0);
assert.ok(report.coverage.preparedConfigRefs > 0);
assert.ok(report.coverage.canonicalToPreparedFiles >= 0);
assert.ok(report.coverage.pipelineStages >= 0);
assert.ok(report.coverage.confirmedOverwrites >= 0);
for (const finding of report.findings) {
  assert.equal(typeof finding.id, 'string');
  assert.equal(typeof finding.title, 'string');
  assert.ok(Array.isArray(finding.evidence));
}

const falsePositiveIds = [
  'ui-api-method:PUT:/api/media/library?:',
  'ui-api-method:POST:/api/rich-media/upload:',
  'ui-api-method:POST:/api/engagement/part-request-image:'
];
for (const prefix of falsePositiveIds) {
  assert.equal(
    report.findings.some(finding => finding.id.startsWith(prefix)),
    false,
    `Known Site Auditor false-positive returned: ${prefix}`
  );
}

const fixedContractIds = [
  'rich-text:page-section-rendered-as-plain-text',
  'rich-text:storefront-css-parity-missing',
  'rich-text:runtime-probe-marker-missing',
  'live-editor:stale-page-snapshot',
  'live-editor:persistence-roundtrip-unverified'
];
for (const id of fixedContractIds) {
  assert.equal(
    report.findings.some(finding => finding.id === id),
    false,
    `Fixed rich/live contract regressed: ${id}`
  );
}
assert.equal(report.findings.some(finding => finding.id === 'production-bundle-hash-mismatch'), false);

const tracePath = path.join(process.cwd(), 'AUDIT_PIPELINE_TRACE.json');
assert.ok(fs.existsSync(tracePath), 'AUDIT_PIPELINE_TRACE.json must be generated by prepare:source');
const trace = JSON.parse(fs.readFileSync(tracePath, 'utf8'));
assert.equal(trace.schemaVersion, 1);
assert.ok(Array.isArray(trace.stages));
assert.ok(Array.isArray(trace.prepared?.routes));
assert.ok(trace.prepared.routes.length > 0);
assert.ok(Array.isArray(trace.prepared?.apiCalls));
assert.ok(trace.prepared.apiCalls.length > 0);
assert.ok(Array.isArray(trace.prepared?.configRefs));
assert.ok(trace.prepared.configRefs.length > 0);
assert.ok(Array.isArray(trace.confirmedOverwrites));
assert.match(String(trace.production?.serverBundleSha256 || ''), /^[0-9a-f]{64}$/);
assert.match(String(trace.production?.distIndexSha256 || ''), /^[0-9a-f]{64}$/);

const pluginRoot = path.join(process.cwd(), 'extensions/site-auditor');
assert.ok(fs.existsSync(path.join(pluginRoot, 'plugin.json')));
assert.ok(fs.existsSync(path.join(pluginRoot, 'client/index.js')));
assert.ok(fs.existsSync(path.join(pluginRoot, 'assets/auditor.css')));
const manifest = JSON.parse(fs.readFileSync(path.join(pluginRoot, 'plugin.json'), 'utf8'));
assert.equal(manifest.id, 'site-auditor');
assert.equal(manifest.type, 'plugin');
assert.equal(manifest.clientEntry, 'client/index.js');
console.log(`Site Auditor 2.2 smoke passed with ${report.findings.length} findings, ${report.coverage.pipelineStages} traced stages, ${report.coverage.confirmedOverwrites} confirmed overwrites, rich/live contracts healthy, production bundle verified.`);
